version: "3.8"

services:
  mongodb:
    image: mongo:6.0.3
    build: ./
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoroot
      - MONGO_INITDB_ROOT_PASSWORD=mongoroot_password
    volumes:
      - ./db:/data/db
  app:
    depends_on:
      - mongodb
    build: ./app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - DB=mongodb://mongoroot:mongoroot_password@mongodb/viopsuite


